# Generated by Django - allow_resubmit for single submission rule

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0007_course_subject_content_optional_content_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='allow_resubmit',
            field=models.BooleanField(default=False, verbose_name='Autoriser une nouvelle soumission'),
        ),
    ]
