# Generated by Django 4.2.7 on 2026-03-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0008_assignmentsubmission_allow_resubmit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='academic_year',
            field=models.CharField(max_length=20, verbose_name='Année scolaire'),
        ),
        migrations.AlterField(
            model_name='course',
            name='academic_year',
            field=models.CharField(max_length=20, verbose_name='Année scolaire'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='academic_year',
            field=models.CharField(max_length=20, verbose_name='Année scolaire'),
        ),
    ]
