# Generated by Django 4.2.7 on 2026-03-12 11:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0012_add_meeting_groups_and_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='promoters',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'PROMOTER'}, related_name='promoted_schools', to=settings.AUTH_USER_MODEL, verbose_name='Promoteurs'),
        ),
        migrations.AddField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('MATERNELLE', 'Maternelle'), ('PRIMAIRE', 'Primaire'), ('HUMANITAIRE', 'Humanitaire')], default='PRIMAIRE', help_text='Détermine les classes disponibles : Maternelle (1ère-3ème), Primaire (1ère-6ème), Humanitaire (7ème-8ème, 1ère-4ème).', max_length=20, verbose_name="Type d'école"),
        ),
        migrations.AlterField(
            model_name='school',
            name='academic_year',
            field=models.CharField(default='2024-2025', max_length=20, verbose_name='Année scolaire'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='academic_year',
            field=models.CharField(max_length=20, verbose_name='Année scolaire'),
        ),
    ]
