# Generated by Django 4.2.7 on 2026-03-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0013_school_promoters_school_school_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsubject',
            name='domain',
            field=models.CharField(blank=True, help_text='Ex. DOMAINE DES SCIENCES, DOMAINE DES LANGUES, DOMAINE DES ARTS…', max_length=100, null=True, verbose_name='Domaine (bulletin RDC)'),
        ),
        migrations.AddField(
            model_name='school',
            name='commune',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Commune / Territoire'),
        ),
        migrations.AddField(
            model_name='school',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Province'),
        ),
    ]
