# Generated by Django 4.2.7 on 2026-03-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0014_classsubject_domain_school_commune_school_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='address_avenue',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Avenue'),
        ),
        migrations.AddField(
            model_name='school',
            name='address_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro'),
        ),
        migrations.AddField(
            model_name='school',
            name='address_quarter',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Quartier'),
        ),
    ]
