# Generated by Django 4.2.7 on 2026-03-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('GRADE', 'Note'), ('ATTENDANCE', 'Présence'), ('ASSIGNMENT', 'Devoir'), ('PAYMENT', 'Paiement'), ('ANNOUNCEMENT', 'Annonce'), ('MEETING', 'Réunion'), ('DISCIPLINE', 'Discipline'), ('MESSAGE', 'Message'), ('QUIZ', 'Interrogation / Examen'), ('GENERAL', 'Général')], max_length=20, verbose_name='Type'),
        ),
    ]
