# Generated by Django 4.2.7 on 2026-03-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoringreport',
            name='academic_progress',
            field=models.TextField(verbose_name='Progrès scolaire'),
        ),
    ]
