# Generated by Django 4.2.7 on 2026-03-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='academic_year',
            field=models.CharField(max_length=20, verbose_name='Année scolaire'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur école'), ('TEACHER', 'Enseignant'), ('PARENT', 'Parent'), ('STUDENT', 'Élève'), ('ACCOUNTANT', 'Comptable'), ('DISCIPLINE_OFFICER', 'Chargé de discipline'), ('PROMOTER', 'Promoteur')], max_length=20, verbose_name='Rôle'),
        ),
    ]
