# Generated by Django 4.2.7 on 2026-03-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_student_academic_year_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=10, null=True, verbose_name='Genre'),
        ),
        migrations.AddField(
            model_name='student',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lieu de naissance'),
        ),
    ]
