# Generated by Django 4.2.7 on 2026-03-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_student_gender_student_place_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address_avenue',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Avenue'),
        ),
        migrations.AddField(
            model_name='user',
            name='address_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='user',
            name='address_commune',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Commune'),
        ),
        migrations.AddField(
            model_name='user',
            name='address_country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='user',
            name='address_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro'),
        ),
        migrations.AddField(
            model_name='user',
            name='address_province',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Province'),
        ),
        migrations.AddField(
            model_name='user',
            name='address_quarter',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Quartier'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse (libre)'),
        ),
    ]
