# Generated by Django 4.2.7 on 2026-03-13 10:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0014_classsubject_domain_school_commune_school_province'),
        ('accounts', '0006_student_gender_student_place_of_birth'),
        ('academics', '0007_add_discipline_request'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicyear',
            options={'verbose_name': 'Année scolaire', 'verbose_name_plural': 'Années scolaires'},
        ),
        migrations.AlterField(
            model_name='grade',
            name='academic_year',
            field=models.CharField(max_length=20, verbose_name='Année scolaire'),
        ),
        migrations.AlterField(
            model_name='gradebulletin',
            name='academic_year',
            field=models.CharField(max_length=20, verbose_name='Année scolaire'),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='academic_year',
            field=models.CharField(max_length=20, verbose_name='Année scolaire'),
        ),
        migrations.CreateModel(
            name='EvaluationGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20, verbose_name='Année scolaire')),
                ('semester', models.CharField(choices=[('S1', 'Premier semestre'), ('S2', 'Second semestre')], max_length=2, verbose_name='Semestre')),
                ('period', models.PositiveSmallIntegerField(verbose_name='Période (1 à 4)')),
                ('eval_type', models.CharField(choices=[('HOMEWORK', 'Devoir'), ('QUIZ', 'Interrogation'), ('EXAM', 'Examen')], max_length=10, verbose_name="Type d'évaluation")),
                ('score', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Note obtenue')),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Note sur')),
                ('source', models.CharField(default='MANUAL', max_length=20, verbose_name='Source')),
                ('source_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='ID source')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_grades', to='schools.schoolclass', verbose_name='Classe')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_grades', to='accounts.student', verbose_name='Élève')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_grades', to='schools.subject', verbose_name='Matière')),
            ],
            options={
                'verbose_name': 'Évaluation détaillée',
                'verbose_name_plural': 'Évaluations détaillées',
                'ordering': ['-created_at'],
            },
        ),
    ]
