# Generated by Django 4.2.7 on 2026-03-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_alter_academicyear_options_alter_grade_academic_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationgrade',
            name='title',
            field=models.CharField(blank=True, default='', help_text="Texte libre saisi par l'enseignant (ex. Devoir d'algèbre).", max_length=255, verbose_name="Titre de l'évaluation"),
        ),
    ]
