# Generated by Django 4.2.7 on 2026-03-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_schoolpaymentmethod_paymenttransaction_remove_flutterwave'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feetype',
            options={'ordering': ['school', 'name'], 'verbose_name': 'Type de frais', 'verbose_name_plural': 'Types de frais'},
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='academic_year',
            field=models.CharField(max_length=20, verbose_name='Année scolaire'),
        ),
    ]
