# Generated by Django 4.2.7 on 2026-03-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0003_add_mother_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentapplication',
            name='academic_year',
            field=models.CharField(max_length=20, verbose_name='Année scolaire'),
        ),
        migrations.AlterField(
            model_name='reenrollment',
            name='academic_year',
            field=models.CharField(max_length=20, verbose_name='Année scolaire'),
        ),
    ]
