# Generated by Django 4.2.7 on 2026-03-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0004_alter_enrollmentapplication_academic_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentapplication',
            name='address_avenue',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Avenue'),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='address_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='address_commune',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Commune'),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='address_country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='address_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro'),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='address_province',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Province'),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='address_quarter',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Quartier'),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='parent_address_avenue',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Avenue (parent)'),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='parent_address_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville (parent)'),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='parent_address_commune',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Commune (parent)'),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='parent_address_country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pays (parent)'),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='parent_address_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro (parent)'),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='parent_address_province',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Province (parent)'),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='parent_address_quarter',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Quartier (parent)'),
        ),
    ]
